const AppException = require('./AppException');

class NotFoundException extends AppException {
  constructor(message = 'Recurso n√£o encontrado') {
    super(404, message);
  }
}

module.exports = NotFoundException;
