const AppException = require('./AppException');

class NotFoundException extends AppException {
  constructor(message = 'Recurso n√£o encontrado') {
    super(message, 404);
  }
}

module.exports = NotFoundException;
